import './globals.css'
import Navigation from '@/components/Navigation'



export const metadata = {
  title: 'My Portfolio and API',
  description: 'Generated by create next app',
  keywords: "next,react,app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
  <link rel='stylesheet' href='https://bootswatch.com/5/vapor/bootstrap.min.css'/>
</head>
      <body>
     <Navigation/>
     <div className='container p-4'>     

  {children}
  <hr />
  <p>Consumo de API con Next.js: He desarrollado esta Breve aplicacion web utilizando Next.js y he integrado exitosamente una API externa para obtener y mostrar datos en tiempo real. Esta habilidad me permitio crear una aplicacion dinámica y visible al usuario</p>
  <p>En este caso lo he compartido con un breve portafolio mio en las siguientes secciónes:</p></div>
    
     </body>
    </html>
  )
}
